---
- name: Clone repository
  git:
    repo: "{{ repo_url }}"
    dest: /var/www/market2hand
    version: main
  become_user: market2hand

- name: Setup virtualenv
  pip:
    virtualenv: /var/www/market2hand/venv
    virtualenv_command: python3 -m venv
    requirements: /var/www/market2hand/requirements.txt
  become_user: market2hand

- name: Install gunicorn
  pip:
    name: gunicorn
    virtualenv: /var/www/market2hand/venv
  become_user: market2hand

- name: Create .env file
  template:
    src: env.j2
    dest: /var/www/market2hand/.env
    owner: market2hand
    group: market2hand
    mode: '0600'

- name: Configure supervisor
  template:
    src: supervisor.conf.j2
    dest: /etc/supervisor/conf.d/market2hand.conf
  notify: restart supervisor 